### ISSUE TITLE
[DEV] Support OAuth 2.0

### ISSUE THREAD

**Issue by b20132367** [handicrafty/sixteen-backend#3]
# Motivation

Spring Security 를 활용해 OAuth 2.0 을 지원합니다.
Apple 로그인을 지원하는 것이 목표입니다.

# To do

- [ ] Spring Security 정리
    - [ ] General Authentication Flow
    - [ ] OAuth Authentication Flow
- [ ] 설계
- [ ] 논의
- [ ] 구현
    - [ ] 애플
    - [x] 네이버
    - [x] 카카오
    - [x] 구글

# Considerations

Apple 로그인은 개발자 프로그램 가입이 필요합니다.
연간 이용료가 10만원이 넘기 때문에, 합의가 필요할 것 같네요.
개발 자체는 타사를 이용해 진행하고,
앱 출시가 필요할 때 맞춰서 하는 것도 방법이겠습니다.

**Comment by ksundong** [comment]
이거 아마 승혁님이 개발자 프로그램 가입 되어계실 거에요! 한 번 확인해보시죠!

**Comment by b20132367** [comment]
# Authorization Code Grant

## 정의

- resource owner
- client
- authorization server

## 흐름

1. client 가 resource owner 를 authorization server 로 유도한다.
    - 이 때, client 정보를 전달한다.
2. authorization server 는 resource owner 를 인증한다.
3. authorization server 가 resource owner 를 client 로 유도한다.
    - 이 때, authorization code 를 전달한다.
4. client 가 authorization server 로부터 access token 을 받아온다.
    - 이 때, authorization code 를 사용한다.

# 예시

1. `sixteen` 이 `홍길동` 을 `네이버아이디로로그인` 으로 유도한다.
    - 이 때, `client_id`, `redirect_uri` 를 전달한다.
2. `네이버아이디로로그인` 은 `홍길동` 을 인증한다.
3. `네이버아이디로로그인` 은 `홍길동` 을 `sixteen` 으로 유도한다.
    - 이 때, authorization code 를 전달한다.
4. `sixteen` 은 `네이버아이디로로그인` 으로부터 access token 을 받아온다.
    - 이 때, `client_id`, `client_secret`, `code` 를 전달한다.

## 참조

- https://datatracker.ietf.org/doc/html/rfc6749#section-4.1
- https://developers.naver.com/docs/login/devguide/devguide.md

**Comment by b20132367** [comment]
# OAuth2

## 방식 1

- POST /oauth2/${identifier:-uuid}
  - idempotent 한 방식
- Broser-based redirections
- 브라우저 창이 닫힌다
- GET /oauth2/${identifier}

## 방식 2

- SDK 를 사용해서, authorization code 를 획득한다
  - 앱 or 내부 프로토콜을 이용해서, 브라우저 없이 가능하다
- POST /oauth2/authorfization/${code}

**Comment by b20132367** [comment]
https://github.com/handicrafty/sixteen-backend/pull/8#issuecomment-1704030925 에서 논의한 것처럼, 구현 방식을 변경합니다. 이 이슈는 닫겠습니다.
